// Aletheia 接口契约 —— Protobuf 定义
//
// 本文件是 docs/05-接口契约与数据模型.md 的机器可读形式。
//
// 契约管理原则（05 §0）：
//   C1 契约定死，实现可变。双语言（Go/Python）切换、模块重写均不得改动本文件定义的结构与语义。
//   C2 失败必须显式。所有接口的失败语义是 fail-closed —— 不确定 = 拒绝。
//   C3 证据优先。任何产出"发现"的接口，其返回结构必须能反向追溯到 EvidenceEntry。
//   C4 版本化。包名带 v1，破坏性变更升 v2，旧版本保留至少一个 minor 周期。
//   C5 单向依赖。层间依赖只允许 L0→L1→L2→L3→L4 方向。
//
// 维护铁律（09 §R1）：
//   本文件已冻结。任何变更必须走独立 PR，标题前缀 `contract:`，且需双人 review
//   （其中一人必须是 M4 反幻觉负责人）。
//
// 标注约定：
//   [frozen]  该字段/消息的字段与语义逐字来自 05，不得改动。
//   [derived] 05 在 service RPC 中引用了该消息名，但未给出完整字段表。
//             此处按 RPC 语义补齐最小字段集，仅用于让契约可编译。
//             本标注不影响冻结状态 —— 派生字段同样需要 `contract:` 流程才能修改。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: aleth/v1/aletheia.proto

package alethv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IngestService_Execute_FullMethodName      = "/aleth.v1.IngestService/Execute"
	IngestService_ListAdapters_FullMethodName = "/aleth.v1.IngestService/ListAdapters"
	IngestService_ValidateTool_FullMethodName = "/aleth.v1.IngestService/ValidateTool"
)

// IngestServiceClient is the client API for IngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IngestService（05 §2.2）[frozen]
// 禁止事项：不提供接受原始命令行字符串的接口。
type IngestServiceClient interface {
	// 执行工具并产出光谱。内部完成：范围校验 → 参数渲染 → 沙箱执行 → 解析 → 折叠
	Execute(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*EvidenceSpectrum, error)
	// 注册/查询工具适配器
	ListAdapters(ctx context.Context, in *ListAdaptersRequest, opts ...grpc.CallOption) (*ListAdaptersResponse, error)
	// 校验工具可用性与版本（fail-closed：版本不匹配返回 TOOL_VERSION_MISMATCH）
	ValidateTool(ctx context.Context, in *ValidateToolRequest, opts ...grpc.CallOption) (*ValidateToolResponse, error)
}

type ingestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIngestServiceClient(cc grpc.ClientConnInterface) IngestServiceClient {
	return &ingestServiceClient{cc}
}

func (c *ingestServiceClient) Execute(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (*EvidenceSpectrum, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvidenceSpectrum)
	err := c.cc.Invoke(ctx, IngestService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) ListAdapters(ctx context.Context, in *ListAdaptersRequest, opts ...grpc.CallOption) (*ListAdaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdaptersResponse)
	err := c.cc.Invoke(ctx, IngestService_ListAdapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingestServiceClient) ValidateTool(ctx context.Context, in *ValidateToolRequest, opts ...grpc.CallOption) (*ValidateToolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateToolResponse)
	err := c.cc.Invoke(ctx, IngestService_ValidateTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngestServiceServer is the server API for IngestService service.
// All implementations must embed UnimplementedIngestServiceServer
// for forward compatibility.
//
// IngestService（05 §2.2）[frozen]
// 禁止事项：不提供接受原始命令行字符串的接口。
type IngestServiceServer interface {
	// 执行工具并产出光谱。内部完成：范围校验 → 参数渲染 → 沙箱执行 → 解析 → 折叠
	Execute(context.Context, *ToolRequest) (*EvidenceSpectrum, error)
	// 注册/查询工具适配器
	ListAdapters(context.Context, *ListAdaptersRequest) (*ListAdaptersResponse, error)
	// 校验工具可用性与版本（fail-closed：版本不匹配返回 TOOL_VERSION_MISMATCH）
	ValidateTool(context.Context, *ValidateToolRequest) (*ValidateToolResponse, error)
	mustEmbedUnimplementedIngestServiceServer()
}

// UnimplementedIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIngestServiceServer struct{}

func (UnimplementedIngestServiceServer) Execute(context.Context, *ToolRequest) (*EvidenceSpectrum, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedIngestServiceServer) ListAdapters(context.Context, *ListAdaptersRequest) (*ListAdaptersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdapters not implemented")
}
func (UnimplementedIngestServiceServer) ValidateTool(context.Context, *ValidateToolRequest) (*ValidateToolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTool not implemented")
}
func (UnimplementedIngestServiceServer) mustEmbedUnimplementedIngestServiceServer() {}
func (UnimplementedIngestServiceServer) testEmbeddedByValue()                       {}

// UnsafeIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngestServiceServer will
// result in compilation errors.
type UnsafeIngestServiceServer interface {
	mustEmbedUnimplementedIngestServiceServer()
}

func RegisterIngestServiceServer(s grpc.ServiceRegistrar, srv IngestServiceServer) {
	// If the following call pancis, it indicates UnimplementedIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IngestService_ServiceDesc, srv)
}

func _IngestService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).Execute(ctx, req.(*ToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_ListAdapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).ListAdapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_ListAdapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).ListAdapters(ctx, req.(*ListAdaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IngestService_ValidateTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateToolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngestServiceServer).ValidateTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IngestService_ValidateTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngestServiceServer).ValidateTool(ctx, req.(*ValidateToolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IngestService_ServiceDesc is the grpc.ServiceDesc for IngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.IngestService",
	HandlerType: (*IngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _IngestService_Execute_Handler,
		},
		{
			MethodName: "ListAdapters",
			Handler:    _IngestService_ListAdapters_Handler,
		},
		{
			MethodName: "ValidateTool",
			Handler:    _IngestService_ValidateTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	PrismService_Ingest_FullMethodName         = "/aleth.v1.PrismService/Ingest"
	PrismService_Project_FullMethodName        = "/aleth.v1.PrismService/Project"
	PrismService_SnapshotAt_FullMethodName     = "/aleth.v1.PrismService/SnapshotAt"
	PrismService_CreateBranch_FullMethodName   = "/aleth.v1.PrismService/CreateBranch"
	PrismService_RollbackBranch_FullMethodName = "/aleth.v1.PrismService/RollbackBranch"
	PrismService_MergeBranch_FullMethodName    = "/aleth.v1.PrismService/MergeBranch"
)

// PrismServiceClient is the client API for PrismService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PrismService（05 §3.3）[frozen]
type PrismServiceClient interface {
	// 写入光谱（幂等：相同 spectrum_id 重复写入不产生副作用）
	Ingest(ctx context.Context, in *EvidenceSpectrum, opts ...grpc.CallOption) (*IngestResult, error)
	// 投影：按焦点与孔径返回子图（供 L2 使用，见 §4）
	Project(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*ProjectedSubgraph, error)
	// 时间回放：返回 T 时刻的认知状态
	SnapshotAt(ctx context.Context, in *SnapshotAtRequest, opts ...grpc.CallOption) (*ProjectedSubgraph, error)
	// 假设分支管理
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*BranchInfo, error)
	RollbackBranch(ctx context.Context, in *RollbackBranchRequest, opts ...grpc.CallOption) (*RollbackResult, error)
	MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeResult, error)
}

type prismServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrismServiceClient(cc grpc.ClientConnInterface) PrismServiceClient {
	return &prismServiceClient{cc}
}

func (c *prismServiceClient) Ingest(ctx context.Context, in *EvidenceSpectrum, opts ...grpc.CallOption) (*IngestResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResult)
	err := c.cc.Invoke(ctx, PrismService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) Project(ctx context.Context, in *ProjectRequest, opts ...grpc.CallOption) (*ProjectedSubgraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectedSubgraph)
	err := c.cc.Invoke(ctx, PrismService_Project_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) SnapshotAt(ctx context.Context, in *SnapshotAtRequest, opts ...grpc.CallOption) (*ProjectedSubgraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectedSubgraph)
	err := c.cc.Invoke(ctx, PrismService_SnapshotAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*BranchInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BranchInfo)
	err := c.cc.Invoke(ctx, PrismService_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) RollbackBranch(ctx context.Context, in *RollbackBranchRequest, opts ...grpc.CallOption) (*RollbackResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResult)
	err := c.cc.Invoke(ctx, PrismService_RollbackBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prismServiceClient) MergeBranch(ctx context.Context, in *MergeBranchRequest, opts ...grpc.CallOption) (*MergeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeResult)
	err := c.cc.Invoke(ctx, PrismService_MergeBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrismServiceServer is the server API for PrismService service.
// All implementations must embed UnimplementedPrismServiceServer
// for forward compatibility.
//
// PrismService（05 §3.3）[frozen]
type PrismServiceServer interface {
	// 写入光谱（幂等：相同 spectrum_id 重复写入不产生副作用）
	Ingest(context.Context, *EvidenceSpectrum) (*IngestResult, error)
	// 投影：按焦点与孔径返回子图（供 L2 使用，见 §4）
	Project(context.Context, *ProjectRequest) (*ProjectedSubgraph, error)
	// 时间回放：返回 T 时刻的认知状态
	SnapshotAt(context.Context, *SnapshotAtRequest) (*ProjectedSubgraph, error)
	// 假设分支管理
	CreateBranch(context.Context, *CreateBranchRequest) (*BranchInfo, error)
	RollbackBranch(context.Context, *RollbackBranchRequest) (*RollbackResult, error)
	MergeBranch(context.Context, *MergeBranchRequest) (*MergeResult, error)
	mustEmbedUnimplementedPrismServiceServer()
}

// UnimplementedPrismServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPrismServiceServer struct{}

func (UnimplementedPrismServiceServer) Ingest(context.Context, *EvidenceSpectrum) (*IngestResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedPrismServiceServer) Project(context.Context, *ProjectRequest) (*ProjectedSubgraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Project not implemented")
}
func (UnimplementedPrismServiceServer) SnapshotAt(context.Context, *SnapshotAtRequest) (*ProjectedSubgraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SnapshotAt not implemented")
}
func (UnimplementedPrismServiceServer) CreateBranch(context.Context, *CreateBranchRequest) (*BranchInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedPrismServiceServer) RollbackBranch(context.Context, *RollbackBranchRequest) (*RollbackResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackBranch not implemented")
}
func (UnimplementedPrismServiceServer) MergeBranch(context.Context, *MergeBranchRequest) (*MergeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeBranch not implemented")
}
func (UnimplementedPrismServiceServer) mustEmbedUnimplementedPrismServiceServer() {}
func (UnimplementedPrismServiceServer) testEmbeddedByValue()                      {}

// UnsafePrismServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrismServiceServer will
// result in compilation errors.
type UnsafePrismServiceServer interface {
	mustEmbedUnimplementedPrismServiceServer()
}

func RegisterPrismServiceServer(s grpc.ServiceRegistrar, srv PrismServiceServer) {
	// If the following call pancis, it indicates UnimplementedPrismServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PrismService_ServiceDesc, srv)
}

func _PrismService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceSpectrum)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).Ingest(ctx, req.(*EvidenceSpectrum))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_Project_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).Project(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_Project_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).Project(ctx, req.(*ProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_SnapshotAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).SnapshotAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_SnapshotAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).SnapshotAt(ctx, req.(*SnapshotAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_RollbackBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).RollbackBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_RollbackBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).RollbackBranch(ctx, req.(*RollbackBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrismService_MergeBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrismServiceServer).MergeBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PrismService_MergeBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrismServiceServer).MergeBranch(ctx, req.(*MergeBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrismService_ServiceDesc is the grpc.ServiceDesc for PrismService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrismService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.PrismService",
	HandlerType: (*PrismServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _PrismService_Ingest_Handler,
		},
		{
			MethodName: "Project",
			Handler:    _PrismService_Project_Handler,
		},
		{
			MethodName: "SnapshotAt",
			Handler:    _PrismService_SnapshotAt_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _PrismService_CreateBranch_Handler,
		},
		{
			MethodName: "RollbackBranch",
			Handler:    _PrismService_RollbackBranch_Handler,
		},
		{
			MethodName: "MergeBranch",
			Handler:    _PrismService_MergeBranch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	ApertureService_Assemble_FullMethodName  = "/aleth.v1.ApertureService/Assemble"
	ApertureService_Autofocus_FullMethodName = "/aleth.v1.ApertureService/Autofocus"
)

// ApertureServiceClient is the client API for ApertureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ApertureService（05 §4.2）[frozen]
type ApertureServiceClient interface {
	// 装配上下文（核心接口）
	Assemble(ctx context.Context, in *AssembleRequest, opts ...grpc.CallOption) (*ContextBundle, error)
	// 自动对焦：给定任务与假设，返回焦点
	Autofocus(ctx context.Context, in *AutofocusRequest, opts ...grpc.CallOption) (*AutofocusResult, error)
}

type apertureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApertureServiceClient(cc grpc.ClientConnInterface) ApertureServiceClient {
	return &apertureServiceClient{cc}
}

func (c *apertureServiceClient) Assemble(ctx context.Context, in *AssembleRequest, opts ...grpc.CallOption) (*ContextBundle, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextBundle)
	err := c.cc.Invoke(ctx, ApertureService_Assemble_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apertureServiceClient) Autofocus(ctx context.Context, in *AutofocusRequest, opts ...grpc.CallOption) (*AutofocusResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutofocusResult)
	err := c.cc.Invoke(ctx, ApertureService_Autofocus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApertureServiceServer is the server API for ApertureService service.
// All implementations must embed UnimplementedApertureServiceServer
// for forward compatibility.
//
// ApertureService（05 §4.2）[frozen]
type ApertureServiceServer interface {
	// 装配上下文（核心接口）
	Assemble(context.Context, *AssembleRequest) (*ContextBundle, error)
	// 自动对焦：给定任务与假设，返回焦点
	Autofocus(context.Context, *AutofocusRequest) (*AutofocusResult, error)
	mustEmbedUnimplementedApertureServiceServer()
}

// UnimplementedApertureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApertureServiceServer struct{}

func (UnimplementedApertureServiceServer) Assemble(context.Context, *AssembleRequest) (*ContextBundle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Assemble not implemented")
}
func (UnimplementedApertureServiceServer) Autofocus(context.Context, *AutofocusRequest) (*AutofocusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Autofocus not implemented")
}
func (UnimplementedApertureServiceServer) mustEmbedUnimplementedApertureServiceServer() {}
func (UnimplementedApertureServiceServer) testEmbeddedByValue()                         {}

// UnsafeApertureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApertureServiceServer will
// result in compilation errors.
type UnsafeApertureServiceServer interface {
	mustEmbedUnimplementedApertureServiceServer()
}

func RegisterApertureServiceServer(s grpc.ServiceRegistrar, srv ApertureServiceServer) {
	// If the following call pancis, it indicates UnimplementedApertureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApertureService_ServiceDesc, srv)
}

func _ApertureService_Assemble_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssembleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApertureServiceServer).Assemble(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApertureService_Assemble_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApertureServiceServer).Assemble(ctx, req.(*AssembleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApertureService_Autofocus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutofocusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApertureServiceServer).Autofocus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApertureService_Autofocus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApertureServiceServer).Autofocus(ctx, req.(*AutofocusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApertureService_ServiceDesc is the grpc.ServiceDesc for ApertureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApertureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.ApertureService",
	HandlerType: (*ApertureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Assemble",
			Handler:    _ApertureService_Assemble_Handler,
		},
		{
			MethodName: "Autofocus",
			Handler:    _ApertureService_Autofocus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	LedgerService_Append_FullMethodName              = "/aleth.v1.LedgerService/Append"
	LedgerService_ValidateAssertion_FullMethodName   = "/aleth.v1.LedgerService/ValidateAssertion"
	LedgerService_RecordSideEffect_FullMethodName    = "/aleth.v1.LedgerService/RecordSideEffect"
	LedgerService_Reproduce_FullMethodName           = "/aleth.v1.LedgerService/Reproduce"
	LedgerService_TraceFinding_FullMethodName        = "/aleth.v1.LedgerService/TraceFinding"
	LedgerService_ReportHallucination_FullMethodName = "/aleth.v1.LedgerService/ReportHallucination"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LedgerService（05 §5.3）[frozen]
// 本服务是系统里唯一有权说"这个发现成立"的模块（modules/M4）。
type LedgerServiceClient interface {
	// 追加证据（append-only，不可修改/删除）
	Append(ctx context.Context, in *AppendEvidenceRequest, opts ...grpc.CallOption) (*AppendEvidenceResult, error)
	// 断言校验（四道闸门）
	ValidateAssertion(ctx context.Context, in *ValidateAssertionRequest, opts ...grpc.CallOption) (*ValidateAssertionResult, error)
	// 记录副作用观测
	RecordSideEffect(ctx context.Context, in *RecordSideEffectRequest, opts ...grpc.CallOption) (*RecordSideEffectResult, error)
	// 触发独立复现
	Reproduce(ctx context.Context, in *ReproduceRequest, opts ...grpc.CallOption) (*ReproduceResult, error)
	// 查询某 finding 的完整证据链
	TraceFinding(ctx context.Context, in *TraceFindingRequest, opts ...grpc.CallOption) (*TracedEvidenceChain, error)
	// 幻觉计数
	ReportHallucination(ctx context.Context, in *ReportHallucinationRequest, opts ...grpc.CallOption) (*HallucinationState, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) Append(ctx context.Context, in *AppendEvidenceRequest, opts ...grpc.CallOption) (*AppendEvidenceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEvidenceResult)
	err := c.cc.Invoke(ctx, LedgerService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ValidateAssertion(ctx context.Context, in *ValidateAssertionRequest, opts ...grpc.CallOption) (*ValidateAssertionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateAssertionResult)
	err := c.cc.Invoke(ctx, LedgerService_ValidateAssertion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) RecordSideEffect(ctx context.Context, in *RecordSideEffectRequest, opts ...grpc.CallOption) (*RecordSideEffectResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordSideEffectResult)
	err := c.cc.Invoke(ctx, LedgerService_RecordSideEffect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) Reproduce(ctx context.Context, in *ReproduceRequest, opts ...grpc.CallOption) (*ReproduceResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReproduceResult)
	err := c.cc.Invoke(ctx, LedgerService_Reproduce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) TraceFinding(ctx context.Context, in *TraceFindingRequest, opts ...grpc.CallOption) (*TracedEvidenceChain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TracedEvidenceChain)
	err := c.cc.Invoke(ctx, LedgerService_TraceFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReportHallucination(ctx context.Context, in *ReportHallucinationRequest, opts ...grpc.CallOption) (*HallucinationState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HallucinationState)
	err := c.cc.Invoke(ctx, LedgerService_ReportHallucination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
//
// LedgerService（05 §5.3）[frozen]
// 本服务是系统里唯一有权说"这个发现成立"的模块（modules/M4）。
type LedgerServiceServer interface {
	// 追加证据（append-only，不可修改/删除）
	Append(context.Context, *AppendEvidenceRequest) (*AppendEvidenceResult, error)
	// 断言校验（四道闸门）
	ValidateAssertion(context.Context, *ValidateAssertionRequest) (*ValidateAssertionResult, error)
	// 记录副作用观测
	RecordSideEffect(context.Context, *RecordSideEffectRequest) (*RecordSideEffectResult, error)
	// 触发独立复现
	Reproduce(context.Context, *ReproduceRequest) (*ReproduceResult, error)
	// 查询某 finding 的完整证据链
	TraceFinding(context.Context, *TraceFindingRequest) (*TracedEvidenceChain, error)
	// 幻觉计数
	ReportHallucination(context.Context, *ReportHallucinationRequest) (*HallucinationState, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) Append(context.Context, *AppendEvidenceRequest) (*AppendEvidenceResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedLedgerServiceServer) ValidateAssertion(context.Context, *ValidateAssertionRequest) (*ValidateAssertionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAssertion not implemented")
}
func (UnimplementedLedgerServiceServer) RecordSideEffect(context.Context, *RecordSideEffectRequest) (*RecordSideEffectResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordSideEffect not implemented")
}
func (UnimplementedLedgerServiceServer) Reproduce(context.Context, *ReproduceRequest) (*ReproduceResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reproduce not implemented")
}
func (UnimplementedLedgerServiceServer) TraceFinding(context.Context, *TraceFindingRequest) (*TracedEvidenceChain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TraceFinding not implemented")
}
func (UnimplementedLedgerServiceServer) ReportHallucination(context.Context, *ReportHallucinationRequest) (*HallucinationState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportHallucination not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call pancis, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Append(ctx, req.(*AppendEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ValidateAssertion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAssertionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ValidateAssertion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ValidateAssertion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ValidateAssertion(ctx, req.(*ValidateAssertionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_RecordSideEffect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSideEffectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).RecordSideEffect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_RecordSideEffect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).RecordSideEffect(ctx, req.(*RecordSideEffectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_Reproduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReproduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).Reproduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_Reproduce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).Reproduce(ctx, req.(*ReproduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_TraceFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceFindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).TraceFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_TraceFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).TraceFinding(ctx, req.(*TraceFindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReportHallucination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportHallucinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReportHallucination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_ReportHallucination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReportHallucination(ctx, req.(*ReportHallucinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _LedgerService_Append_Handler,
		},
		{
			MethodName: "ValidateAssertion",
			Handler:    _LedgerService_ValidateAssertion_Handler,
		},
		{
			MethodName: "RecordSideEffect",
			Handler:    _LedgerService_RecordSideEffect_Handler,
		},
		{
			MethodName: "Reproduce",
			Handler:    _LedgerService_Reproduce_Handler,
		},
		{
			MethodName: "TraceFinding",
			Handler:    _LedgerService_TraceFinding_Handler,
		},
		{
			MethodName: "ReportHallucination",
			Handler:    _LedgerService_ReportHallucination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	TerminationService_RequestTermination_FullMethodName = "/aleth.v1.TerminationService/RequestTermination"
)

// TerminationServiceClient is the client API for TerminationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TerminationService（05 §5.4）[frozen]
// 硬约束：RequestTermination 是全系统唯一的会话终止入口（除熔断外）。
// 任何直接 return / raise SystemExit / 关闭 session 的路径都是 P0 缺陷（09 §R6）。
type TerminationServiceClient interface {
	// agent 请求终止 —— 无权限自行终止
	RequestTermination(ctx context.Context, in *TerminationRequest, opts ...grpc.CallOption) (*TerminationDecision, error)
}

type terminationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminationServiceClient(cc grpc.ClientConnInterface) TerminationServiceClient {
	return &terminationServiceClient{cc}
}

func (c *terminationServiceClient) RequestTermination(ctx context.Context, in *TerminationRequest, opts ...grpc.CallOption) (*TerminationDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminationDecision)
	err := c.cc.Invoke(ctx, TerminationService_RequestTermination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerminationServiceServer is the server API for TerminationService service.
// All implementations must embed UnimplementedTerminationServiceServer
// for forward compatibility.
//
// TerminationService（05 §5.4）[frozen]
// 硬约束：RequestTermination 是全系统唯一的会话终止入口（除熔断外）。
// 任何直接 return / raise SystemExit / 关闭 session 的路径都是 P0 缺陷（09 §R6）。
type TerminationServiceServer interface {
	// agent 请求终止 —— 无权限自行终止
	RequestTermination(context.Context, *TerminationRequest) (*TerminationDecision, error)
	mustEmbedUnimplementedTerminationServiceServer()
}

// UnimplementedTerminationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerminationServiceServer struct{}

func (UnimplementedTerminationServiceServer) RequestTermination(context.Context, *TerminationRequest) (*TerminationDecision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestTermination not implemented")
}
func (UnimplementedTerminationServiceServer) mustEmbedUnimplementedTerminationServiceServer() {}
func (UnimplementedTerminationServiceServer) testEmbeddedByValue()                            {}

// UnsafeTerminationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerminationServiceServer will
// result in compilation errors.
type UnsafeTerminationServiceServer interface {
	mustEmbedUnimplementedTerminationServiceServer()
}

func RegisterTerminationServiceServer(s grpc.ServiceRegistrar, srv TerminationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTerminationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerminationService_ServiceDesc, srv)
}

func _TerminationService_RequestTermination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminationServiceServer).RequestTermination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminationService_RequestTermination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminationServiceServer).RequestTermination(ctx, req.(*TerminationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TerminationService_ServiceDesc is the grpc.ServiceDesc for TerminationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerminationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.TerminationService",
	HandlerType: (*TerminationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestTermination",
			Handler:    _TerminationService_RequestTermination_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	OrchestratorService_Plan_FullMethodName             = "/aleth.v1.OrchestratorService/Plan"
	OrchestratorService_NextReady_FullMethodName        = "/aleth.v1.OrchestratorService/NextReady"
	OrchestratorService_ReportTaskResult_FullMethodName = "/aleth.v1.OrchestratorService/ReportTaskResult"
	OrchestratorService_Refine_FullMethodName           = "/aleth.v1.OrchestratorService/Refine"
	OrchestratorService_Checkpoint_FullMethodName       = "/aleth.v1.OrchestratorService/Checkpoint"
	OrchestratorService_Rewind_FullMethodName           = "/aleth.v1.OrchestratorService/Rewind"
	OrchestratorService_Fork_FullMethodName             = "/aleth.v1.OrchestratorService/Fork"
)

// OrchestratorServiceClient is the client API for OrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrchestratorService（05 §6.2）[frozen]
// 关键设计：NextReady 的实现不得调用 LLM —— 它是拓扑排序 + 资源约束求解。
type OrchestratorServiceClient interface {
	Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*TaskGraph, error)
	NextReady(ctx context.Context, in *NextReadyRequest, opts ...grpc.CallOption) (*NextReadyResponse, error)
	ReportTaskResult(ctx context.Context, in *ReportTaskResultRequest, opts ...grpc.CallOption) (*TaskUpdateResult, error)
	Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*TaskGraph, error)
	Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointInfo, error)
	Rewind(ctx context.Context, in *RewindRequest, opts ...grpc.CallOption) (*RewindResult, error)
	Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResult, error)
}

type orchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrchestratorServiceClient(cc grpc.ClientConnInterface) OrchestratorServiceClient {
	return &orchestratorServiceClient{cc}
}

func (c *orchestratorServiceClient) Plan(ctx context.Context, in *PlanRequest, opts ...grpc.CallOption) (*TaskGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskGraph)
	err := c.cc.Invoke(ctx, OrchestratorService_Plan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) NextReady(ctx context.Context, in *NextReadyRequest, opts ...grpc.CallOption) (*NextReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NextReadyResponse)
	err := c.cc.Invoke(ctx, OrchestratorService_NextReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) ReportTaskResult(ctx context.Context, in *ReportTaskResultRequest, opts ...grpc.CallOption) (*TaskUpdateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskUpdateResult)
	err := c.cc.Invoke(ctx, OrchestratorService_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) Refine(ctx context.Context, in *RefineRequest, opts ...grpc.CallOption) (*TaskGraph, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskGraph)
	err := c.cc.Invoke(ctx, OrchestratorService_Refine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) Checkpoint(ctx context.Context, in *CheckpointRequest, opts ...grpc.CallOption) (*CheckpointInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckpointInfo)
	err := c.cc.Invoke(ctx, OrchestratorService_Checkpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) Rewind(ctx context.Context, in *RewindRequest, opts ...grpc.CallOption) (*RewindResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RewindResult)
	err := c.cc.Invoke(ctx, OrchestratorService_Rewind_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orchestratorServiceClient) Fork(ctx context.Context, in *ForkRequest, opts ...grpc.CallOption) (*ForkResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForkResult)
	err := c.cc.Invoke(ctx, OrchestratorService_Fork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrchestratorServiceServer is the server API for OrchestratorService service.
// All implementations must embed UnimplementedOrchestratorServiceServer
// for forward compatibility.
//
// OrchestratorService（05 §6.2）[frozen]
// 关键设计：NextReady 的实现不得调用 LLM —— 它是拓扑排序 + 资源约束求解。
type OrchestratorServiceServer interface {
	Plan(context.Context, *PlanRequest) (*TaskGraph, error)
	NextReady(context.Context, *NextReadyRequest) (*NextReadyResponse, error)
	ReportTaskResult(context.Context, *ReportTaskResultRequest) (*TaskUpdateResult, error)
	Refine(context.Context, *RefineRequest) (*TaskGraph, error)
	Checkpoint(context.Context, *CheckpointRequest) (*CheckpointInfo, error)
	Rewind(context.Context, *RewindRequest) (*RewindResult, error)
	Fork(context.Context, *ForkRequest) (*ForkResult, error)
	mustEmbedUnimplementedOrchestratorServiceServer()
}

// UnimplementedOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrchestratorServiceServer struct{}

func (UnimplementedOrchestratorServiceServer) Plan(context.Context, *PlanRequest) (*TaskGraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Plan not implemented")
}
func (UnimplementedOrchestratorServiceServer) NextReady(context.Context, *NextReadyRequest) (*NextReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextReady not implemented")
}
func (UnimplementedOrchestratorServiceServer) ReportTaskResult(context.Context, *ReportTaskResultRequest) (*TaskUpdateResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedOrchestratorServiceServer) Refine(context.Context, *RefineRequest) (*TaskGraph, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Refine not implemented")
}
func (UnimplementedOrchestratorServiceServer) Checkpoint(context.Context, *CheckpointRequest) (*CheckpointInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkpoint not implemented")
}
func (UnimplementedOrchestratorServiceServer) Rewind(context.Context, *RewindRequest) (*RewindResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rewind not implemented")
}
func (UnimplementedOrchestratorServiceServer) Fork(context.Context, *ForkRequest) (*ForkResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fork not implemented")
}
func (UnimplementedOrchestratorServiceServer) mustEmbedUnimplementedOrchestratorServiceServer() {}
func (UnimplementedOrchestratorServiceServer) testEmbeddedByValue()                             {}

// UnsafeOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrchestratorServiceServer will
// result in compilation errors.
type UnsafeOrchestratorServiceServer interface {
	mustEmbedUnimplementedOrchestratorServiceServer()
}

func RegisterOrchestratorServiceServer(s grpc.ServiceRegistrar, srv OrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrchestratorService_ServiceDesc, srv)
}

func _OrchestratorService_Plan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Plan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Plan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Plan(ctx, req.(*PlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_NextReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).NextReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_NextReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).NextReady(ctx, req.(*NextReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTaskResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).ReportTaskResult(ctx, req.(*ReportTaskResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_Refine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Refine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Refine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Refine(ctx, req.(*RefineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_Checkpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Checkpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Checkpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Checkpoint(ctx, req.(*CheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_Rewind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RewindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Rewind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Rewind_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Rewind(ctx, req.(*RewindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrchestratorService_Fork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrchestratorServiceServer).Fork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrchestratorService_Fork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrchestratorServiceServer).Fork(ctx, req.(*ForkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrchestratorService_ServiceDesc is the grpc.ServiceDesc for OrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.OrchestratorService",
	HandlerType: (*OrchestratorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Plan",
			Handler:    _OrchestratorService_Plan_Handler,
		},
		{
			MethodName: "NextReady",
			Handler:    _OrchestratorService_NextReady_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _OrchestratorService_ReportTaskResult_Handler,
		},
		{
			MethodName: "Refine",
			Handler:    _OrchestratorService_Refine_Handler,
		},
		{
			MethodName: "Checkpoint",
			Handler:    _OrchestratorService_Checkpoint_Handler,
		},
		{
			MethodName: "Rewind",
			Handler:    _OrchestratorService_Rewind_Handler,
		},
		{
			MethodName: "Fork",
			Handler:    _OrchestratorService_Fork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	ScopeService_Check_FullMethodName     = "/aleth.v1.ScopeService/Check"
	ScopeService_LoadScope_FullMethodName = "/aleth.v1.ScopeService/LoadScope"
)

// ScopeServiceClient is the client API for ScopeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScopeService（05 §6.3）[frozen]
type ScopeServiceClient interface {
	// 三重校验：network / tool_param / post_dns
	Check(ctx context.Context, in *ScopeCheckRequest, opts ...grpc.CallOption) (*ScopeCheckResult, error)
	LoadScope(ctx context.Context, in *LoadScopeRequest, opts ...grpc.CallOption) (*ScopeInfo, error)
}

type scopeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScopeServiceClient(cc grpc.ClientConnInterface) ScopeServiceClient {
	return &scopeServiceClient{cc}
}

func (c *scopeServiceClient) Check(ctx context.Context, in *ScopeCheckRequest, opts ...grpc.CallOption) (*ScopeCheckResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScopeCheckResult)
	err := c.cc.Invoke(ctx, ScopeService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scopeServiceClient) LoadScope(ctx context.Context, in *LoadScopeRequest, opts ...grpc.CallOption) (*ScopeInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScopeInfo)
	err := c.cc.Invoke(ctx, ScopeService_LoadScope_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScopeServiceServer is the server API for ScopeService service.
// All implementations must embed UnimplementedScopeServiceServer
// for forward compatibility.
//
// ScopeService（05 §6.3）[frozen]
type ScopeServiceServer interface {
	// 三重校验：network / tool_param / post_dns
	Check(context.Context, *ScopeCheckRequest) (*ScopeCheckResult, error)
	LoadScope(context.Context, *LoadScopeRequest) (*ScopeInfo, error)
	mustEmbedUnimplementedScopeServiceServer()
}

// UnimplementedScopeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScopeServiceServer struct{}

func (UnimplementedScopeServiceServer) Check(context.Context, *ScopeCheckRequest) (*ScopeCheckResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedScopeServiceServer) LoadScope(context.Context, *LoadScopeRequest) (*ScopeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LoadScope not implemented")
}
func (UnimplementedScopeServiceServer) mustEmbedUnimplementedScopeServiceServer() {}
func (UnimplementedScopeServiceServer) testEmbeddedByValue()                      {}

// UnsafeScopeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScopeServiceServer will
// result in compilation errors.
type UnsafeScopeServiceServer interface {
	mustEmbedUnimplementedScopeServiceServer()
}

func RegisterScopeServiceServer(s grpc.ServiceRegistrar, srv ScopeServiceServer) {
	// If the following call pancis, it indicates UnimplementedScopeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScopeService_ServiceDesc, srv)
}

func _ScopeService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScopeCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeServiceServer).Check(ctx, req.(*ScopeCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScopeService_LoadScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScopeServiceServer).LoadScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScopeService_LoadScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScopeServiceServer).LoadScope(ctx, req.(*LoadScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScopeService_ServiceDesc is the grpc.ServiceDesc for ScopeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScopeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.ScopeService",
	HandlerType: (*ScopeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _ScopeService_Check_Handler,
		},
		{
			MethodName: "LoadScope",
			Handler:    _ScopeService_LoadScope_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	GovernorService_Reserve_FullMethodName      = "/aleth.v1.GovernorService/Reserve"
	GovernorService_Consume_FullMethodName      = "/aleth.v1.GovernorService/Consume"
	GovernorService_State_FullMethodName        = "/aleth.v1.GovernorService/State"
	GovernorService_CheckCircuit_FullMethodName = "/aleth.v1.GovernorService/CheckCircuit"
)

// GovernorServiceClient is the client API for GovernorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GovernorService（05 §6.3）[frozen]
type GovernorServiceClient interface {
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResult, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*BudgetState, error)
	State(ctx context.Context, in *BudgetStateRequest, opts ...grpc.CallOption) (*BudgetState, error)
	CheckCircuit(ctx context.Context, in *CircuitCheckRequest, opts ...grpc.CallOption) (*CircuitState, error)
}

type governorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGovernorServiceClient(cc grpc.ClientConnInterface) GovernorServiceClient {
	return &governorServiceClient{cc}
}

func (c *governorServiceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResult)
	err := c.cc.Invoke(ctx, GovernorService_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governorServiceClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*BudgetState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetState)
	err := c.cc.Invoke(ctx, GovernorService_Consume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governorServiceClient) State(ctx context.Context, in *BudgetStateRequest, opts ...grpc.CallOption) (*BudgetState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BudgetState)
	err := c.cc.Invoke(ctx, GovernorService_State_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *governorServiceClient) CheckCircuit(ctx context.Context, in *CircuitCheckRequest, opts ...grpc.CallOption) (*CircuitState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CircuitState)
	err := c.cc.Invoke(ctx, GovernorService_CheckCircuit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GovernorServiceServer is the server API for GovernorService service.
// All implementations must embed UnimplementedGovernorServiceServer
// for forward compatibility.
//
// GovernorService（05 §6.3）[frozen]
type GovernorServiceServer interface {
	Reserve(context.Context, *ReserveRequest) (*ReserveResult, error)
	Consume(context.Context, *ConsumeRequest) (*BudgetState, error)
	State(context.Context, *BudgetStateRequest) (*BudgetState, error)
	CheckCircuit(context.Context, *CircuitCheckRequest) (*CircuitState, error)
	mustEmbedUnimplementedGovernorServiceServer()
}

// UnimplementedGovernorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGovernorServiceServer struct{}

func (UnimplementedGovernorServiceServer) Reserve(context.Context, *ReserveRequest) (*ReserveResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedGovernorServiceServer) Consume(context.Context, *ConsumeRequest) (*BudgetState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedGovernorServiceServer) State(context.Context, *BudgetStateRequest) (*BudgetState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method State not implemented")
}
func (UnimplementedGovernorServiceServer) CheckCircuit(context.Context, *CircuitCheckRequest) (*CircuitState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckCircuit not implemented")
}
func (UnimplementedGovernorServiceServer) mustEmbedUnimplementedGovernorServiceServer() {}
func (UnimplementedGovernorServiceServer) testEmbeddedByValue()                         {}

// UnsafeGovernorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GovernorServiceServer will
// result in compilation errors.
type UnsafeGovernorServiceServer interface {
	mustEmbedUnimplementedGovernorServiceServer()
}

func RegisterGovernorServiceServer(s grpc.ServiceRegistrar, srv GovernorServiceServer) {
	// If the following call pancis, it indicates UnimplementedGovernorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GovernorService_ServiceDesc, srv)
}

func _GovernorService_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernorServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernorService_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernorServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernorService_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernorServiceServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernorService_Consume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernorServiceServer).Consume(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernorService_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BudgetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernorServiceServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernorService_State_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernorServiceServer).State(ctx, req.(*BudgetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GovernorService_CheckCircuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CircuitCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GovernorServiceServer).CheckCircuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GovernorService_CheckCircuit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GovernorServiceServer).CheckCircuit(ctx, req.(*CircuitCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GovernorService_ServiceDesc is the grpc.ServiceDesc for GovernorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GovernorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.GovernorService",
	HandlerType: (*GovernorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reserve",
			Handler:    _GovernorService_Reserve_Handler,
		},
		{
			MethodName: "Consume",
			Handler:    _GovernorService_Consume_Handler,
		},
		{
			MethodName: "State",
			Handler:    _GovernorService_State_Handler,
		},
		{
			MethodName: "CheckCircuit",
			Handler:    _GovernorService_CheckCircuit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	SandboxService_Execute_FullMethodName    = "/aleth.v1.SandboxService/Execute"
	SandboxService_SignExecId_FullMethodName = "/aleth.v1.SandboxService/SignExecId"
)

// SandboxServiceClient is the client API for SandboxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SandboxService（05 §6.3）[frozen]
type SandboxServiceClient interface {
	// 执行 + 签发 exec_id（唯一合法签发者）
	Execute(ctx context.Context, in *SandboxExecRequest, opts ...grpc.CallOption) (*SandboxExecResult, error)
	SignExecId(ctx context.Context, in *SignExecIdRequest, opts ...grpc.CallOption) (*SignedExecId, error)
}

type sandboxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxServiceClient(cc grpc.ClientConnInterface) SandboxServiceClient {
	return &sandboxServiceClient{cc}
}

func (c *sandboxServiceClient) Execute(ctx context.Context, in *SandboxExecRequest, opts ...grpc.CallOption) (*SandboxExecResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SandboxExecResult)
	err := c.cc.Invoke(ctx, SandboxService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxServiceClient) SignExecId(ctx context.Context, in *SignExecIdRequest, opts ...grpc.CallOption) (*SignedExecId, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignedExecId)
	err := c.cc.Invoke(ctx, SandboxService_SignExecId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxServiceServer is the server API for SandboxService service.
// All implementations must embed UnimplementedSandboxServiceServer
// for forward compatibility.
//
// SandboxService（05 §6.3）[frozen]
type SandboxServiceServer interface {
	// 执行 + 签发 exec_id（唯一合法签发者）
	Execute(context.Context, *SandboxExecRequest) (*SandboxExecResult, error)
	SignExecId(context.Context, *SignExecIdRequest) (*SignedExecId, error)
	mustEmbedUnimplementedSandboxServiceServer()
}

// UnimplementedSandboxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxServiceServer struct{}

func (UnimplementedSandboxServiceServer) Execute(context.Context, *SandboxExecRequest) (*SandboxExecResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedSandboxServiceServer) SignExecId(context.Context, *SignExecIdRequest) (*SignedExecId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignExecId not implemented")
}
func (UnimplementedSandboxServiceServer) mustEmbedUnimplementedSandboxServiceServer() {}
func (UnimplementedSandboxServiceServer) testEmbeddedByValue()                        {}

// UnsafeSandboxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxServiceServer will
// result in compilation errors.
type UnsafeSandboxServiceServer interface {
	mustEmbedUnimplementedSandboxServiceServer()
}

func RegisterSandboxServiceServer(s grpc.ServiceRegistrar, srv SandboxServiceServer) {
	// If the following call pancis, it indicates UnimplementedSandboxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxService_ServiceDesc, srv)
}

func _SandboxService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).Execute(ctx, req.(*SandboxExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxService_SignExecId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignExecIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxServiceServer).SignExecId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxService_SignExecId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxServiceServer).SignExecId(ctx, req.(*SignExecIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxService_ServiceDesc is the grpc.ServiceDesc for SandboxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.SandboxService",
	HandlerType: (*SandboxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _SandboxService_Execute_Handler,
		},
		{
			MethodName: "SignExecId",
			Handler:    _SandboxService_SignExecId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}

const (
	GatewayService_Tokenize_FullMethodName     = "/aleth.v1.GatewayService/Tokenize"
	GatewayService_Detokenize_FullMethodName   = "/aleth.v1.GatewayService/Detokenize"
	GatewayService_ScanOutbound_FullMethodName = "/aleth.v1.GatewayService/ScanOutbound"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService（05 §6.4）[frozen]
type GatewayServiceClient interface {
	Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResult, error)
	Detokenize(ctx context.Context, in *DetokenizeRequest, opts ...grpc.CallOption) (*DetokenizeResult, error)
	ScanOutbound(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResult, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) Tokenize(ctx context.Context, in *TokenizeRequest, opts ...grpc.CallOption) (*TokenizeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeResult)
	err := c.cc.Invoke(ctx, GatewayService_Tokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) Detokenize(ctx context.Context, in *DetokenizeRequest, opts ...grpc.CallOption) (*DetokenizeResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetokenizeResult)
	err := c.cc.Invoke(ctx, GatewayService_Detokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ScanOutbound(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanResult)
	err := c.cc.Invoke(ctx, GatewayService_ScanOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService（05 §6.4）[frozen]
type GatewayServiceServer interface {
	Tokenize(context.Context, *TokenizeRequest) (*TokenizeResult, error)
	Detokenize(context.Context, *DetokenizeRequest) (*DetokenizeResult, error)
	ScanOutbound(context.Context, *ScanRequest) (*ScanResult, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) Tokenize(context.Context, *TokenizeRequest) (*TokenizeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tokenize not implemented")
}
func (UnimplementedGatewayServiceServer) Detokenize(context.Context, *DetokenizeRequest) (*DetokenizeResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Detokenize not implemented")
}
func (UnimplementedGatewayServiceServer) ScanOutbound(context.Context, *ScanRequest) (*ScanResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScanOutbound not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_Tokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Tokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Tokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Tokenize(ctx, req.(*TokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_Detokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetokenizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).Detokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_Detokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).Detokenize(ctx, req.(*DetokenizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ScanOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ScanOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ScanOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ScanOutbound(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aleth.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tokenize",
			Handler:    _GatewayService_Tokenize_Handler,
		},
		{
			MethodName: "Detokenize",
			Handler:    _GatewayService_Detokenize_Handler,
		},
		{
			MethodName: "ScanOutbound",
			Handler:    _GatewayService_ScanOutbound_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aleth/v1/aletheia.proto",
}
